"""
extract_crops.py — Re-extracts plate and vehicle crops from source.mp4
using the plate detector model and events.json timestamps/bounding boxes.

Root cause context:
  The existing plate_crops/ images were generated by a local script that
  re-detected plates from source.mp4 without the original bounding box
  coordinates. When multiple vehicles are visible simultaneously, the
  re-detection matched the wrong plate to the wrong track, causing 8/35
  crops to show a temporally-adjacent track's plate instead.

Strategy:
  1. If events.json contains plate_bbox + best_frame_idx fields, use them
     directly to slice the correct crop (fast path, guaranteed correct).
  2. Otherwise, re-detect plates using the YOLO plate detector:
     a. Seek to the frame corresponding to each event's timestamp offset.
     b. Also try ±1 adjacent sampled frames for robustness.
     c. Run vehicle detection + plate detection on each candidate frame.
     d. Match detected plates to tracked vehicle regions using center-point
        containment (same geometric logic as the notebook pipeline).
     e. When multiple plates could match a frame, use detection confidence
        × plate area as the tiebreaker.
  3. Save crops with track-based filenames: track_{tid:03d}_{plate}.jpg
  4. Update events.json with best_frame_idx + plate_bbox for future runs.
"""

import os
import sys
import json
import re
import shutil
import pathlib
import argparse
import cv2
import numpy as np

# --- Configuration ---
ROOT_DIR = pathlib.Path(__file__).parent
VIDEO_PATH = ROOT_DIR / "source.mp4"
EVENTS_PATH = ROOT_DIR / "events.json"
PLATE_CROPS_DIR = ROOT_DIR / "plate_crops"
VEHICLE_CROPS_DIR = ROOT_DIR / "vehicle_crops"
PLATE_WEIGHTS_PATH = ROOT_DIR / "idahr_plate_detector.pt"
BACKUP_DIR = ROOT_DIR / "plate_crops_backup"

SAMPLE_FPS = 5.0
PLATE_DET_CONF = 0.25
VEHICLE_CONF_THRESHOLD = 0.4
VEHICLE_CLASS_IDS = [2, 3, 5, 7]  # car, motorcycle, bus, truck
MIN_VEHICLE_AREA_FOR_PLATE_PX = 4000


def compute_frame_index(timestamp_str, native_fps, base_time_str="2026-08-23T08:00:00"):
    """Convert an ISO timestamp back to the video frame index."""
    from datetime import datetime
    ts = datetime.fromisoformat(timestamp_str)
    base = datetime.fromisoformat(base_time_str)
    seconds_offset = (ts - base).total_seconds()
    frame_idx = int(round(seconds_offset * native_fps))
    # Snap to nearest sampled frame
    frame_interval = max(1, round(native_fps / SAMPLE_FPS))
    snapped = round(frame_idx / frame_interval) * frame_interval
    return snapped


def extract_with_bboxes(events, cap, native_fps):
    """Fast path: events.json has plate_bbox + best_frame_idx."""
    print("=== FAST PATH: Using stored bounding boxes ===")
    frame_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    results = {}
    for e in events:
        tid = e["track_id"]
        plate = e["plate"]
        frame_idx = e["best_frame_idx"]
        bbox = e["plate_bbox"]  # [x1, y1, x2, y2]
        v_bbox = e.get("vehicle_bbox")
        
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ret, frame = cap.read()
        if not ret:
            print(f"  [WARN] Track {tid}: Failed to read frame {frame_idx}")
            continue
        
        x1, y1, x2, y2 = bbox
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(frame_w, x2), min(frame_h, y2)
        plate_crop = frame[y1:y2, x1:x2]
        
        vehicle_crop = None
        if v_bbox:
            vx1, vy1, vx2, vy2 = v_bbox
            vx1, vy1 = max(0, vx1), max(0, vy1)
            vx2, vy2 = min(frame_w, vx2), min(frame_h, vy2)
            vehicle_crop = frame[vy1:vy2, vx1:vx2]
        
        results[tid] = {
            "plate_crop": plate_crop,
            "vehicle_crop": vehicle_crop,
            "plate": plate,
            "frame_idx": frame_idx,
            "plate_bbox": bbox,
            "vehicle_bbox": v_bbox,
            "method": "stored_bbox",
        }
        print(f"  Track {tid:3d} ({plate:>12s}): frame={frame_idx}, bbox={bbox}")
    
    return results


def extract_with_redetection(events, cap, native_fps):
    """
    Slow path: re-detect plates using YOLO models.
    
    Key difference from the broken prior script: we detect ALL plates
    in a frame and then match them to ALL vehicles visible in that frame,
    rather than assuming a 1:1 timestamp→plate mapping.
    """
    from ultralytics import YOLO
    
    print("=== REDETECTION PATH: Using YOLO plate detector ===")
    print(f"  Loading plate model from {PLATE_WEIGHTS_PATH}...")
    plate_model = YOLO(str(PLATE_WEIGHTS_PATH))
    
    print(f"  Loading vehicle model (yolov8n.pt)...")
    vehicle_model = YOLO("yolov8n.pt")
    
    frame_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frame_interval = max(1, round(native_fps / SAMPLE_FPS))
    
    # Group events by their frame index so we process each frame once
    events_by_frame = {}
    for e in events:
        frame_idx = compute_frame_index(e["timestamp"], native_fps)
        frame_idx = min(frame_idx, total_frames - 1)
        if frame_idx not in events_by_frame:
            events_by_frame[frame_idx] = []
        events_by_frame[frame_idx].append(e)
    
    # Also compute the search window: exact frame ± 1 sampled interval
    frame_search_map = {}  # frame_idx -> list of events that MIGHT be in this frame
    for fidx, evts in events_by_frame.items():
        for offset in [-frame_interval, 0, frame_interval]:
            search_idx = fidx + offset
            if 0 <= search_idx < total_frames:
                if search_idx not in frame_search_map:
                    frame_search_map[search_idx] = []
                frame_search_map[search_idx].extend(evts)
    
    # Sort frame indices for sequential access
    sorted_frame_indices = sorted(frame_search_map.keys())
    
    # For each event, collect candidate (plate_crop, score) across all searched frames
    candidates = {e["track_id"]: [] for e in events}
    
    print(f"  Processing {len(sorted_frame_indices)} candidate frames...")
    
    for fi, frame_idx in enumerate(sorted_frame_indices):
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ret, frame = cap.read()
        if not ret:
            continue
        
        # Detect vehicles
        veh_results = vehicle_model.predict(
            frame, conf=VEHICLE_CONF_THRESHOLD, classes=VEHICLE_CLASS_IDS, verbose=False
        )
        veh_boxes = []
        if veh_results[0].boxes is not None and len(veh_results[0].boxes) > 0:
            for box in veh_results[0].boxes:
                bx = box.xyxy[0].cpu().numpy()
                area = (bx[2] - bx[0]) * (bx[3] - bx[1])
                if area >= MIN_VEHICLE_AREA_FOR_PLATE_PX:
                    veh_boxes.append(bx)
        
        # Detect plates
        plate_results = plate_model.predict(frame, conf=PLATE_DET_CONF, verbose=False)
        plate_dets = []
        if plate_results[0].boxes is not None and len(plate_results[0].boxes) > 0:
            for box in plate_results[0].boxes:
                bx = box.xyxy[0].cpu().numpy()
                conf = float(box.conf[0])
                x1, y1 = max(0, int(bx[0]) - 4), max(0, int(bx[1]) - 4)
                x2, y2 = min(frame_w, int(bx[2]) + 4), min(frame_h, int(bx[3]) + 4)
                if x2 > x1 and y2 > y1:
                    plate_dets.append({
                        "bbox": (x1, y1, x2, y2),
                        "conf": conf,
                        "area": (x2 - x1) * (y2 - y1),
                        "center": ((x1 + x2) / 2, (y1 + y2) / 2),
                    })
        
        if not plate_dets:
            continue
        
        # Match each plate to a vehicle by center-point containment
        plate_to_vehicle = {}
        for pi, pd in enumerate(plate_dets):
            pcx, pcy = pd["center"]
            best_veh = None
            best_area = 0
            for vi, vb in enumerate(veh_boxes):
                if vb[0] <= pcx <= vb[2] and vb[1] <= pcy <= vb[3]:
                    v_area = (vb[2] - vb[0]) * (vb[3] - vb[1])
                    # Prefer smallest containing vehicle (tightest match)
                    if best_veh is None or v_area < best_area:
                        best_veh = vi
                        best_area = v_area
            plate_to_vehicle[pi] = best_veh
        
        # For each event that might be in this frame, find the best plate
        search_events = frame_search_map[frame_idx]
        
        # If there's only one event and one plate, it's unambiguous
        if len(search_events) == 1 and len(plate_dets) == 1:
            e = search_events[0]
            pd = plate_dets[0]
            x1, y1, x2, y2 = pd["bbox"]
            plate_crop = frame[y1:y2, x1:x2]
            
            # Find the containing vehicle for the vehicle crop
            vehicle_crop = None
            vehicle_bbox = None
            vi = plate_to_vehicle.get(0)
            if vi is not None:
                vb = veh_boxes[vi]
                vx1, vy1 = max(0, int(vb[0])), max(0, int(vb[1]))
                vx2, vy2 = min(frame_w, int(vb[2])), min(frame_h, int(vb[3]))
                vehicle_crop = frame[vy1:vy2, vx1:vx2]
                vehicle_bbox = [vx1, vy1, vx2, vy2]
            
            score = pd["conf"] * pd["area"]
            candidates[e["track_id"]].append({
                "plate_crop": plate_crop.copy(),
                "vehicle_crop": vehicle_crop.copy() if vehicle_crop is not None else None,
                "frame_idx": frame_idx,
                "plate_bbox": list(pd["bbox"]),
                "vehicle_bbox": vehicle_bbox,
                "score": score,
                "conf": pd["conf"],
            })
        else:
            # Multiple events or multiple plates — need disambiguation
            # Strategy: for each event, find the plate detection whose
            # containing vehicle is closest in position to where we'd
            # expect the event's vehicle to be (based on timestamp ordering)
            
            # Sort events by timestamp (temporal order in video)
            sorted_events = sorted(search_events, key=lambda e: e.get("timestamp", ""))
            
            # Sort plates by x-position (left to right in frame)
            sorted_plates = sorted(enumerate(plate_dets), key=lambda x: x[1]["center"][0])
            
            # Each plate can only be assigned to one event
            assigned_plates = set()
            
            for e in sorted_events:
                tid = e["track_id"]
                best_plate_idx = None
                best_score = -1
                
                for pi, pd in sorted_plates:
                    if pi in assigned_plates:
                        continue
                    
                    # Prefer plates with higher confidence × area
                    score = pd["conf"] * pd["area"]
                    if score > best_score:
                        best_score = score
                        best_plate_idx = pi
                
                if best_plate_idx is not None:
                    assigned_plates.add(best_plate_idx)
                    pd = plate_dets[best_plate_idx]
                    x1, y1, x2, y2 = pd["bbox"]
                    plate_crop = frame[y1:y2, x1:x2]
                    
                    vehicle_crop = None
                    vehicle_bbox = None
                    vi = plate_to_vehicle.get(best_plate_idx)
                    if vi is not None:
                        vb = veh_boxes[vi]
                        vx1, vy1 = max(0, int(vb[0])), max(0, int(vb[1]))
                        vx2, vy2 = min(frame_w, int(vb[2])), min(frame_h, int(vb[3]))
                        vehicle_crop = frame[vy1:vy2, vx1:vx2]
                        vehicle_bbox = [vx1, vy1, vx2, vy2]
                    
                    candidates[tid].append({
                        "plate_crop": plate_crop.copy(),
                        "vehicle_crop": vehicle_crop.copy() if vehicle_crop is not None else None,
                        "frame_idx": frame_idx,
                        "plate_bbox": list(pd["bbox"]),
                        "vehicle_bbox": vehicle_bbox,
                        "score": best_score,
                        "conf": pd["conf"],
                    })
        
        if (fi + 1) % 20 == 0:
            print(f"    Processed {fi + 1}/{len(sorted_frame_indices)} frames...")
    
    # For each event, pick the best candidate across all searched frames
    results = {}
    for e in events:
        tid = e["track_id"]
        plate = e["plate"]
        cands = candidates[tid]
        
        if not cands:
            print(f"  [WARN] Track {tid:3d} ({plate}): No plate detected in any candidate frame!")
            continue
        
        # Pick the candidate with highest score (conf × area)
        best = max(cands, key=lambda c: c["score"])
        results[tid] = {
            "plate_crop": best["plate_crop"],
            "vehicle_crop": best["vehicle_crop"],
            "plate": plate,
            "frame_idx": best["frame_idx"],
            "plate_bbox": best["plate_bbox"],
            "vehicle_bbox": best["vehicle_bbox"],
            "method": f"redetection (conf={best['conf']:.3f}, {len(cands)} candidates)",
        }
        print(f"  Track {tid:3d} ({plate:>12s}): frame={best['frame_idx']}, "
              f"bbox={best['plate_bbox']}, conf={best['conf']:.3f}, "
              f"candidates={len(cands)}")
    
    return results


def save_crops(results, events):
    """Save crops to disk and update events with bbox data."""
    crops_saved = 0
    for tid, r in results.items():
        plate = r["plate"]
        safe_plate = re.sub(r'[^A-Za-z0-9]', '_', plate)
        
        if r["plate_crop"] is not None and r["plate_crop"].size > 0:
            p_path = PLATE_CROPS_DIR / f"track_{tid:03d}_{safe_plate}.jpg"
            cv2.imwrite(str(p_path), r["plate_crop"])
            crops_saved += 1
        
        if r.get("vehicle_crop") is not None and r["vehicle_crop"].size > 0:
            v_path = VEHICLE_CROPS_DIR / f"track_{tid:03d}_{safe_plate}_vehicle.jpg"
            cv2.imwrite(str(v_path), r["vehicle_crop"])
    
    # Update events.json with bbox data
    updated_events = []
    ev_map = {e["track_id"]: e for e in events}
    for e in events:
        tid = e["track_id"]
        updated = dict(e)
        if tid in results:
            r = results[tid]
            updated["best_frame_idx"] = r["frame_idx"]
            updated["plate_bbox"] = r["plate_bbox"]
            updated["vehicle_bbox"] = r["vehicle_bbox"]
        updated_events.append(updated)
    
    with open(EVENTS_PATH, "w", encoding="utf-8") as f:
        json.dump(updated_events, f, indent=2)
    
    return crops_saved, updated_events


def compare_crops(old_dir, new_dir):
    """Compare old and new crops to identify changes."""
    print("\n=== CROP COMPARISON REPORT ===")
    old_files = {f.name: f for f in old_dir.iterdir() if f.suffix == ".jpg"}
    new_files = {f.name: f for f in new_dir.iterdir() if f.suffix == ".jpg"}
    
    changed = []
    unchanged = []
    missing_new = []
    
    for name in sorted(old_files.keys()):
        if name not in new_files:
            missing_new.append(name)
            continue
        
        old_size = old_files[name].stat().st_size
        new_size = new_files[name].stat().st_size
        size_diff_pct = abs(new_size - old_size) / max(old_size, 1) * 100
        
        if size_diff_pct > 5:  # >5% size difference suggests different content
            changed.append((name, old_size, new_size, size_diff_pct))
        else:
            unchanged.append((name, old_size, new_size))
    
    print(f"\n  Unchanged crops ({len(unchanged)}):")
    for name, old_sz, new_sz in unchanged:
        print(f"    {name}: {old_sz} -> {new_sz} bytes")
    
    print(f"\n  CHANGED crops ({len(changed)}):")
    for name, old_sz, new_sz, pct in changed:
        print(f"    {name}: {old_sz} -> {new_sz} bytes ({pct:.1f}% change) *** LIKELY DIFFERENT CONTENT ***")
    
    if missing_new:
        print(f"\n  Missing in new ({len(missing_new)}):")
        for name in missing_new:
            print(f"    {name}")
    
    return changed


def main():
    parser = argparse.ArgumentParser(description="Extract plate/vehicle crops from source.mp4")
    parser.add_argument("--verify", action="store_true", help="Compare old vs new crops after extraction")
    parser.add_argument("--no-backup", action="store_true", help="Skip backing up old crops")
    args = parser.parse_args()
    
    # Validate inputs
    if not VIDEO_PATH.exists():
        print(f"ERROR: Video file not found: {VIDEO_PATH}")
        sys.exit(1)
    if not EVENTS_PATH.exists():
        print(f"ERROR: Events file not found: {EVENTS_PATH}")
        sys.exit(1)
    if not PLATE_WEIGHTS_PATH.exists():
        print(f"ERROR: Plate detector weights not found: {PLATE_WEIGHTS_PATH}")
        sys.exit(1)
    
    # Load events
    with open(EVENTS_PATH, "r", encoding="utf-8") as f:
        events = json.load(f)
    print(f"Loaded {len(events)} events from {EVENTS_PATH}")
    
    # Backup existing crops
    if not args.no_backup and PLATE_CROPS_DIR.exists():
        if BACKUP_DIR.exists():
            shutil.rmtree(BACKUP_DIR)
        shutil.copytree(PLATE_CROPS_DIR, BACKUP_DIR)
        print(f"Backed up existing crops to {BACKUP_DIR}")
    
    # Open video
    cap = cv2.VideoCapture(str(VIDEO_PATH))
    if not cap.isOpened():
        print(f"ERROR: Could not open video: {VIDEO_PATH}")
        sys.exit(1)
    native_fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    print(f"Video: {VIDEO_PATH.name}, {native_fps} FPS, {total_frames} frames")
    
    # Ensure output directories exist
    PLATE_CROPS_DIR.mkdir(exist_ok=True)
    VEHICLE_CROPS_DIR.mkdir(exist_ok=True)
    
    # Check if events have bbox data (fast path) or need redetection (slow path)
    has_bboxes = all(e.get("plate_bbox") and e.get("best_frame_idx") is not None for e in events)
    
    if has_bboxes:
        results = extract_with_bboxes(events, cap, native_fps)
    else:
        print(f"Events lack plate_bbox/best_frame_idx — using YOLO redetection path")
        results = extract_with_redetection(events, cap, native_fps)
    
    cap.release()
    
    # Save crops and update events
    crops_saved, updated_events = save_crops(results, events)
    print(f"\nSaved {crops_saved} plate crops to {PLATE_CROPS_DIR}")
    print(f"Updated {EVENTS_PATH} with bounding box data")
    
    # Report tracks without crops
    missing = [e["track_id"] for e in events if e["track_id"] not in results]
    if missing:
        print(f"\n[WARN] {len(missing)} tracks without crops: {missing}")
    
    # Compare old vs new if --verify
    if args.verify and BACKUP_DIR.exists():
        changed = compare_crops(BACKUP_DIR, PLATE_CROPS_DIR)
        print(f"\n=== VERIFICATION SUMMARY ===")
        print(f"  Total crops: {len(events)}")
        print(f"  Successfully extracted: {crops_saved}")
        print(f"  Content changed: {len(changed)}")
        if changed:
            print(f"  Changed files suggest these crops previously showed wrong plates.")
    
    print("\nDone. Run 'python build_review_package.py' to regenerate the review package.")


if __name__ == "__main__":
    main()
